[package]
name = "hrdf-parser"
version = "0.9.4"
authors = ["Florian Burgener, Orestis Malaspinas"]
edition = "2024"
description = "This library is dedicated to the parsing of the HRDF format. For the moment, it can only parse the Swiss version of the HRDF format."
repository = "https://github.com/urban-travel/hrdf-parser"
license-file = "LICENSE"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
chrono = { version = "0.4.41", features = ["serde"] }
log = "0.4.27"
nom = { version = "8.0.0", features = ["alloc", "std"] }
reqwest = "0.12.22"
rustc-hash = "2.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.141"
sha2 = "0.10.9"
strum = "0.27.2"
strum_macros = "0.27.2"
test-log = "0.2.18"
thiserror = "2.0.17"
tokio = { version = "1.47.0", features = ["macros", "rt", "rt-multi-thread"] }
url = "2.5.4"
zip = "6.0.0"

[dev-dependencies]
flate2 = "1.0.35"
# For -Zminimal-versions
native-tls = "0.2.14"
pretty_assertions = "1.4.1"
serde_json = "1.0.141"

[profile.dev]
opt-level = 3
